name: Publish Patch

# Run 15 minutes after the hour, every hour.
# We use this instead of the top of the hour to avoid heavy-traffic times on github.
on:
  schedule:
    - cron: '*/15 */1 * * *'
  workflow_dispatch

jobs:
  publish_patch:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.7.8
          channel: stable

      - name: Install Shorebird
        run: curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | sh

      - name: Choose Clock Face
        run: |
          # Choose a clock face based on the current hour
          # Even hours = particle
          # Odd hours = generative
          current_hour=$(date +%H)
          if [ $(($current_hour % 2)) -eq "0" ]; then
            clock_face=particle
          else
            clock_face=generative
          fi
          echo $clock_face >> $GITHUB_ENV

      - name: Create Patch
        run: |
          echo "Creating patch with ${{ env.clock_face }}"
          shorebird patch -- --dart-define clock_face=${{ env.clock_face }}
        
