name: Publish Patch

# Run 15 minutes after the hour, every hour.
# We use this instead of the top of the hour to avoid heavy-traffic times on github.
on:
  schedule:
    - cron: '*/15 */1 * * *'
  workflow_dispatch:
  pull_request:

jobs:
  publish_patch:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Install Shorebird
        uses: shorebirdtech/setup-shorebird@v1

      # TODO: move this to setup-shorebird once we've confirmed it works
      - name: Update PATH
        run: echo "PATH=\"/home/runner/.config/shorebird/bin:$PATH\"" >> $"GITHUB_PATH"

      - name: Choose Clock Face
        run: |
          # Choose a clock face based on the current hour
          # Even hours = particle
          # Odd hours = generative
          current_hour=$(date +%H)
          if [ $(($current_hour % 2)) -eq "0" ]; then
            clock_face=particle
          else
            clock_face=generative
          fi
          echo "Using clock face $clock_face"
          echo "clock_face=$clock_face" >> $GITHUB_ENV

      - name: Create Patch
        run: |
          echo "Creating patch with ${{ env.clock_face }}"
          shorebird patch -- --dart-define clock_face=${{ env.clock_face }}
        
