name: Publish Patch

# Run 15 minutes after the hour, every hour.
# We use this instead of the top of the hour to avoid heavy-traffic times on github.
on:
  schedule:
    - cron: '*/15 */1 * * *'
  workflow_dispatch:
  pull_request:

env:
  # Note: this is specific to macOS
  SHOREBIRD_CREDENTIALS_PATH: ~/Library/Application\ Support/shorebird

jobs:
  publish_patch:
    runs-on: macos-latest

    steps:
      - name: Setup Shorebird Credentials
        run: |
          echo "SHOREBIRD_CREDENTIALS_PATH is $SHOREBIRD_CREDENTIALS_PATH"
          mkdir -p $SHOREBIRD_CREDENTIALS_PATH
          touch $SHOREBIRD_CREDENTIALS_PATH/shorebird-session.json
          echo '${{ secrets.SHOREBIRD_CREDENTIALS }}' > "$SHOREBIRD_CREDENTIALS_PATH/shorebird-session.json"

      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Install Shorebird
        uses: shorebirdtech/setup-shorebird@70b705f05278f4af11ea6456d45b5a75d7e1c9a6

      - name: Choose Clock Face
        run: |
          # Choose a clock face based on the current hour
          # Even hours = particle
          # Odd hours = generative
          current_hour=$(date +%H)
          if [ $(($current_hour % 2)) -eq "0" ]; then
            clock_face=particle
          else
            clock_face=generative
          fi
          echo "Using clock face $clock_face"
          echo "clock_face=$clock_face" >> $GITHUB_ENV

      - name: Create Patch
        run: |
          echo "Creating patch with ${{ env.clock_face }} clock face"
          shorebird patch -- --dart-define clock_face=${{ env.clock_face }}
        
